FROM gradle:jdk17-alpine AS builder
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/home/gradle/.gradle \
    gradle build -x test --parallel

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]