FROM gradle:jdk17-alpine AS builder
WORKDIR /app
COPY . /app
RUN gradle build -x test --no-daemon --info --stacktrace

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]