-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE IF NOT EXISTS members_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE NOT NULL,
    role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE NOT NULL
);
-- rollback DROP TABLE members_roles;