-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id),
    category_id BIGINT REFERENCES hubs(id),
    position INTEGER,
    name VARCHAR(255),
    type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE channels;