-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE channels
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT REFERENCES users (id),
    category_id      BIGINT REFERENCES categories (id),
    position         INTEGER,
    name             VARCHAR(255),
    type             VARCHAR(32) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL
);
-- rollback DROP TABLE channels;