-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE messages
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id        BIGINT REFERENCES users (id)                      NOT NULL,
    channel_id       BIGINT REFERENCES channels (id) ON DELETE CASCADE NOT NULL,
    content          TEXT,
    created_at       TIMESTAMPTZ                                       NOT NULL,
    last_modified_at TIMESTAMPTZ                                       NOT NULL
);
-- rollback DROP TABLE messages;