-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE message_read_statuses(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    read_at TIMESTAMPTZ,
    UNIQUE (message_id, user_id)
);

-- rollback DROP TABLE message_read_statuses;