-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE media
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key  VARCHAR      NOT NULL,
    extension    VARCHAR      NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size         BIGINT       NOT NULL,
    visibility   VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    created_by   BIGINT REFERENCES users (id)
);
-- rollback DROP TABLE message_read_statuses;