-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE user_avatars
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media (id) ON DELETE CASCADE
);
-- rollback DROP TABLE message_read_statuses;