-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE hub_avatars
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id BIGINT REFERENCES hubs(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE
);
-- rollback DROP TABLE message_read_statuses;