-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE message_attachments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE
);
-- rollback DROP TABLE message_read_statuses;