-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    last_activity TIMESTAMP NOT NULL,
    is_active BOOLEAN NOT NULL,
    fingerprint VARCHAR(255) NOT NULL,
    ip_address VARCHAR(16) NOT NULL,
    device_info VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE IF EXISTS user_sessions;
