-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE IF NOT EXISTS tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_token VARCHAR(255) NOT NULL,
    fingerprint VARCHAR(255) NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT false,
    expires_at TIMESTAMP NOT NULL,
    type VARCHAR(20) NOT NULL,
    user_id BIGINT REFERENCES users(id)
);
-- rollback DROP TABLE IF EXISTS tokens;
