-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR NOT NULL,
    type VARCHAR(10) NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT false,
    expires_at TIMESTAMPTZ NOT NULL,
    user_session_id BIGINT REFERENCES user_sessions(id),
    created_at TIMESTAMPTZ NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL
);
-- rollback DROP TABLE IF EXISTS tokens;
