-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE hubs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    owner_id         BIGINT REFERENCES users (id),
    type             VARCHAR(10)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    last_modified_at TIMESTAMPTZ  NOT NULL
);
-- rollback DROP TABLE hubs;