-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE hubs(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    owner_id BIGINT REFERENCES users(id),
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE hubs;