-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE categories
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id           BIGINT REFERENCES hubs (id) ON DELETE CASCADE NOT NULL,
    name             VARCHAR(50)                                   NOT NULL,
    position         INTEGER                                       NOT NULL,
    created_at       TIMESTAMPTZ                                   NOT NULL,
    last_modified_at TIMESTAMPTZ                                   NOT NULL
);
-- rollback DROP TABLE categories;