-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE IF NOT EXISTS members(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id BIGINT REFERENCES hubs(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    joined_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE members;