-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE IF NOT EXISTS invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id BIGINT REFERENCES hubs(id) ON DELETE CASCADE NOT NULL,
    created_by_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    max_uses INTEGER,
    current_uses INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE invites;