-- liquibase formatted sql

-- changeset laterna:1
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id BIGINT REFERENCES hubs(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    permissions TEXT NOT NULL,
    color VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP NOT NULL
);
-- rollback DROP TABLE roles;